### ISSUE TITLE
DoH resolver

### ISSUE THREAD

**Issue by unclejacki** [bepass-org/tunl#12]
the configuration will look like this:

```toml
[dns]
nameserver = "https://1.1.1.1/dns-query"
path = "/dns-query"
```

- [ ] caching queries using cloudflare's KV storage
